production:
  adapter: postgresql
  encoding: unicode
  database: runforjoy_production
  username: postgres
  password: demo_aa
  host: localhost
  port: 5432



development:
  adapter: postgresql
  encoding: unicode
  database: runforjoy_development
  username: postgres
  password: demo_aa
  host: localhost
  port: 5432


