production:
  adapter: postgresql
  encoding: unicode
  database: runforjoy_production
  username: bbsoft0
  password: <%= ENV['runforjoy_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432



development:
  adapter: postgresql
  encoding: unicode
  database: runforjoy_development
  username: bbsoft0
  password: bbsoftm
  host: localhost
  port: 5432


