production:
  adapter: postgresql
  encoding: unicode
  database: runforjoy_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: srv-captain--postgres-db
  timeout: 5000
  port: 5432



development:
  adapter: postgresql
  encoding: unicode
  database: runforjoy_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: srv-captain--postgres-db
  timeout: 5000
  port: 5432


